# Use the README file as a reference to customize settings.

DailyMenu:
  fields:
    default: id, date, breakfast, lunch, dinner, breakfast_photo, lunch_photo, dinner_photo
    form: date, breakfast, lunch, dinner, breakfast_photo, lunch_photo, dinner_photo
  relationships: 
  application: Application
