# Use the README file as a reference to customize settings.

User:
  fields:
    default: email, active, activation_code, activation_start
    form: email, active, activation_code, activation_start
  relationships: 
  application: Application
